# Site settings
title: SynerzyTech
email: shuvrow@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
headerTitle: When Sky Is The Limit
baseurl: /synerzy
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: SynerzyTech
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/SynerzyTech
  - title: facebook
    url: http://facebook.com/SynerzyTech
  - title: bitbucket 
    url: http://bitbucket.org/SynerzyTech
  - title: github
    url: http://github.com/SynerzyTech

# Postal address (add as many lines as necessary)
address:
  - line: House 738, West Kazipara
  - line: Mirpur,Dhaka
  
# Credits content
credits: 'Created by SynerzyTech'

# Build settings
markdown: kramdown
permalink: pretty
